#!/usr/bin/env python3
"""Script to index documentation for multiple projects.

Usage:
    python scripts/index_projects.py

This script reads CLAUDE.md and docs/*.md files from each project
directory and indexes them in the Snipara database.
"""

import asyncio
import hashlib
import os
import sys
from pathlib import Path

# Add parent to path to import src modules
sys.path.insert(0, str(Path(__file__).parent.parent))

from prisma import Prisma

# Project configurations
PROJECTS = {
    "proj_snipara_001": {
        "name": "Snipara",
        "base_path": "/Users/alopez/Devs/RLMSaas",
        "docs_patterns": ["CLAUDE.md", "docs/**/*.md", "specs.md", "ROADMAP.md"],
    },
    "cmkkyqccj0006px3hs0hwx2l2": {
        "name": "DubGrr",
        "base_path": "/Users/alopez/Devs/dubgrr",
        "docs_patterns": ["CLAUDE.md", "docs/**/*.md"],
    },
    "proj_swaploom_001": {
        "name": "SwapLoom",
        "base_path": "/Users/alopez/Devs/SwapLoom",
        "docs_patterns": ["CLAUDE.md", "docs/**/*.md"],
    },
    "proj_zorai_001": {
        "name": "Zorai",
        "base_path": "/Users/alopez/Devs/zorai",
        "docs_patterns": ["CLAUDE.md", "docs/**/*.md"],
    },
}


def compute_hash(content: str) -> str:
    """Compute SHA256 hash of content."""
    return hashlib.sha256(content.encode()).hexdigest()


def find_docs(base_path: str, patterns: list[str]) -> list[Path]:
    """Find all documentation files matching patterns."""
    base = Path(base_path)
    docs = []

    for pattern in patterns:
        if "**" in pattern:
            # Glob pattern
            docs.extend(base.glob(pattern))
        else:
            # Direct file
            path = base / pattern
            if path.exists():
                docs.append(path)

    # Filter to only .md files and exclude hidden files
    docs = [
        d for d in docs
        if d.suffix == ".md"
        and not any(part.startswith(".") for part in d.parts)
    ]

    return sorted(set(docs))


async def upsert_document(
    db: Prisma,
    project_id: str,
    file_path: Path,
    base_path: str
) -> dict:
    """Insert or update a document in the database."""
    content = file_path.read_text(encoding="utf-8")
    relative_path = str(file_path.relative_to(base_path))
    content_hash = compute_hash(content)

    # Check if document exists
    existing = await db.document.find_first(
        where={
            "projectId": project_id,
            "path": relative_path,
        }
    )

    if existing:
        if existing.hash == content_hash:
            return {"action": "skipped", "path": relative_path, "reason": "unchanged"}

        # Update existing document
        await db.document.update(
            where={"id": existing.id},
            data={
                "content": content,
                "hash": content_hash,
                "size": len(content),
            },
        )
        # Delete old chunks (will be regenerated by indexer)
        await db.execute_raw(
            'DELETE FROM document_chunks WHERE "documentId" = $1',
            existing.id,
        )
        return {"action": "updated", "path": relative_path, "id": existing.id}

    # Create new document
    doc = await db.document.create(
        data={
            "projectId": project_id,
            "path": relative_path,
            "content": content,
            "hash": content_hash,
            "size": len(content),
        }
    )
    return {"action": "created", "path": relative_path, "id": doc.id}


async def index_project_documents(db: Prisma, project_id: str) -> int:
    """Index all documents for a project (create chunks with embeddings)."""
    from src.services.indexer import DocumentIndexer

    indexer = DocumentIndexer(db)
    results = await indexer.index_project(project_id)
    return sum(results.values())


async def main():
    """Main entry point."""
    print("=" * 60)
    print("Snipara Documentation Indexer")
    print("=" * 60)

    # Connect to database
    db = Prisma()
    await db.connect()

    try:
        total_docs = 0
        total_chunks = 0

        for project_id, config in PROJECTS.items():
            print(f"\n{'='*60}")
            print(f"Project: {config['name']} ({project_id})")
            print(f"Base path: {config['base_path']}")
            print("=" * 60)

            # Find documentation files
            docs = find_docs(config["base_path"], config["docs_patterns"])
            print(f"Found {len(docs)} documentation files")

            if not docs:
                print("  No documentation files found, skipping...")
                continue

            # Upsert documents
            doc_results = []
            for doc_path in docs:
                try:
                    result = await upsert_document(
                        db, project_id, doc_path, config["base_path"]
                    )
                    doc_results.append(result)
                    status = result["action"]
                    print(f"  [{status.upper():8}] {result['path']}")
                except Exception as e:
                    print(f"  [ERROR   ] {doc_path}: {e}")

            created = sum(1 for r in doc_results if r["action"] == "created")
            updated = sum(1 for r in doc_results if r["action"] == "updated")
            skipped = sum(1 for r in doc_results if r["action"] == "skipped")
            print(f"\nDocuments: {created} created, {updated} updated, {skipped} skipped")
            total_docs += created + updated

            # Index documents (generate embeddings)
            if created > 0 or updated > 0:
                print("\nIndexing documents (generating embeddings)...")
                try:
                    chunk_count = await index_project_documents(db, project_id)
                    print(f"Created {chunk_count} chunks with embeddings")
                    total_chunks += chunk_count
                except Exception as e:
                    print(f"Error indexing: {e}")
                    import traceback
                    traceback.print_exc()

        print(f"\n{'='*60}")
        print("SUMMARY")
        print("=" * 60)
        print(f"Total documents processed: {total_docs}")
        print(f"Total chunks created: {total_chunks}")
        print("=" * 60)

    finally:
        await db.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
